import type { Meta, StoryObj } from '@storybook/react';
import { CodeBlock } from '../../components/sections/code-block';

const meta: Meta<typeof CodeBlock> = {
  title: 'Sections/CodeBlock',
  component: CodeBlock,
  parameters: { layout: 'fullscreen' },
};
export default meta;

type Story = StoryObj<typeof CodeBlock>;

const sampleCode = `import { PolaGate } from '@siracusahq/gate';

// スキーマからSDKを自動生成
const client = PolaGate.createClient({
  tenant: 'my-saas',
  apiKey: process.env.POLASTACK_API_KEY,
});

// 型安全なAPI呼び出し
const users = await client.users.list({
  filter: { role: 'admin' },
  search: 'tanaka',
});`;

export const Centered: Story = {
  render: (_, { globals }) => {
    const isJa = globals.locale === 'ja';
    return (
      <CodeBlock
        eyebrow={isJa ? 'コード例' : 'CODE EXAMPLE'}
        title={isJa ? '10分で統合完了' : 'Integrate in 10 minutes'}
        subtitle={
          isJa
            ? 'PolaGateが生成する型安全なSDKで、すぐに開発を始められます。'
            : 'Start developing immediately with type-safe SDKs generated by PolaGate.'
        }
        code={sampleCode}
        language="typescript"
        filename="app/api/users.ts"
      />
    );
  },
};

/**
 * description を渡すと自動的に横並びになる（layout / alignment prop は削除済み）。
 * 「コードの脇に補足がある」という中身の事実がレイアウトを決める。
 */
export const WithDescription: Story = {
  render: (_, { globals }) => {
    const isJa = globals.locale === 'ja';
    return (
      <CodeBlock
        eyebrow={isJa ? 'デベロッパー体験' : 'DEVELOPER EXPERIENCE'}
        title={isJa ? '型安全なAPI呼び出し' : 'Type-safe API calls'}
        subtitle={
          isJa
            ? 'スキーマ定義からTypeScript SDKを自動生成。手動でのAPI実装は不要です。'
            : 'Auto-generate TypeScript SDK from schema definitions. No manual API implementation needed.'
        }
        description={
          <ul>
            <li>{isJa ? 'スキーマ変更は型エラーで検知' : 'Schema changes surface as type errors'}</li>
            <li>{isJa ? 'OpenAPI と MCP サーバーも同時生成' : 'OpenAPI and MCP server generated too'}</li>
            <li>{isJa ? 'RLS/FLS は DB 最下層で強制' : 'RLS/FLS enforced at the DB layer'}</li>
          </ul>
        }
        code={sampleCode}
        language="typescript"
        filename="app/api/users.ts"
        showLineNumbers
      />
    );
  },
};
