export { LandingPage } from './landing-page';
export {
  defineLandingPage,
  LANDING_PAGE_PATTERNS,
  type LandingPageInput,
  type LandingPageProps,
  type LandingPageEvents,
  type LandingPagePattern,
  type ProductPageInput,
  type PortfolioTopInput,
  type LeadGenInput,
  type CorporateTopInput,
  type CaseStudyListInput,
  type CaseStudyDetailInput,
  type LandingHero,
  type LandingProof,
  type LandingMidCta,
  type LandingClosing,
  type OfferAction,
  type OfferPair,
} from './define-landing-page';
